INSERT INTO countries VALUES (1, '', 'Tunisia');
INSERT INTO country_states VALUES(1, 'Ariana', 1);
INSERT INTO country_states VALUES(2, 'Beja', 1);
INSERT INTO country_states VALUES(3, 'Ben Arous', 1);
INSERT INTO country_states VALUES(4, 'Bizerte', 1);
INSERT INTO country_states VALUES(5, 'Gabes', 1);
INSERT INTO country_states VALUES(6, 'Gafsa', 1);
INSERT INTO country_states VALUES(7, 'Jendouba', 1);
INSERT INTO country_states VALUES(8, 'Kairouan', 1);
INSERT INTO country_states VALUES(9, 'Kaserine', 1);
INSERT INTO country_states VALUES(10, 'Kbeli', 1);
INSERT INTO country_states VALUES(11, 'Kef', 1);
INSERT INTO country_states VALUES(12, 'Mahdia', 1);
INSERT INTO country_states VALUES(13, 'Manouba', 1);
INSERT INTO country_states VALUES(14, 'Mednine', 1);
INSERT INTO country_states VALUES(15, 'Monastir', 1);
INSERT INTO country_states VALUES(16, 'Nabeul', 1);
INSERT INTO country_states VALUES(17, 'Sfax', 1);
INSERT INTO country_states VALUES(18, 'Sidi Bouzid', 1);
INSERT INTO country_states VALUES(19, 'Siliana', 1);
INSERT INTO country_states VALUES(20, 'Sousse', 1);
INSERT INTO country_states VALUES(21, 'Tataouine', 1);
INSERT INTO country_states VALUES(22, 'Touzeur', 1);
INSERT INTO country_states VALUES(23, 'Tunis', 1);
INSERT INTO country_states VALUES(24, 'Zaghouan', 1);
INSERT INTO cities VALUES(1, 'Ariana', 1);
INSERT INTO cities VALUES(2, 'Ettadhamen-Mnihla', 1);
INSERT INTO cities VALUES(3, 'Kalaat el-Andalous', 1);
INSERT INTO cities VALUES(4, 'Raoued', 1);
INSERT INTO cities VALUES(5, 'Sidi Thabet', 1);
INSERT INTO cities VALUES(6, 'La Soukra', 1);
INSERT INTO cities VALUES(7, 'Beja', 2);
INSERT INTO cities VALUES(8, 'El Maagoula', 2);
INSERT INTO cities VALUES(9, 'Goubellat', 2);
INSERT INTO cities VALUES(10, 'Medjez el-Bab', 2);
INSERT INTO cities VALUES(11, 'Nefza', 2);
INSERT INTO cities VALUES(12, 'Teboursouk', 2);
INSERT INTO cities VALUES(13, 'Testour', 2);
INSERT INTO cities VALUES(14, 'Zahret Mediou', 2);
INSERT INTO cities VALUES(15, 'Ben Arous', 3);
INSERT INTO cities VALUES(16, 'Bou Mhel el-Bassatine', 3);
INSERT INTO cities VALUES(17, 'El Mourouj', 3);
INSERT INTO cities VALUES(18, 'Ezzahra', 3);
INSERT INTO cities VALUES(19, 'Hammam Chott', 3);
INSERT INTO cities VALUES(20, 'Hammam Lif', 3);
INSERT INTO cities VALUES(21, 'Khalidia', 3);
INSERT INTO cities VALUES(22, 'Megrine', 3);
INSERT INTO cities VALUES(23, 'Mohamedia-Fouchana', 3);
INSERT INTO cities VALUES(24, 'Mornag', 3);
INSERT INTO cities VALUES(25, 'Rades', 3);
INSERT INTO cities VALUES(26, 'Aousja', 4);
INSERT INTO cities VALUES(27, 'Bizerte', 4);
INSERT INTO cities VALUES(28, 'El Alia', 4);
INSERT INTO cities VALUES(29, 'Ghar El Melh', 4);
INSERT INTO cities VALUES(30, 'Mateur', 4);
INSERT INTO cities VALUES(31, 'Menzel Bourguiba', 4);
INSERT INTO cities VALUES(32, 'Menzel Jemil', 4);
INSERT INTO cities VALUES(33, 'Menzel Abderrahmane', 4);
INSERT INTO cities VALUES(34, 'Metline', 4);
INSERT INTO cities VALUES(35, 'Raf Raf', 4);
INSERT INTO cities VALUES(36, 'Ras Jebel', 4);
INSERT INTO cities VALUES(37, 'Sejenane', 4);
INSERT INTO cities VALUES(38, 'Tinja', 4);
INSERT INTO cities VALUES(39, 'Chenini Nahal', 5);
INSERT INTO cities VALUES(40, 'El Hamma', 5);
INSERT INTO cities VALUES(41, 'Gabes', 5);
INSERT INTO cities VALUES(42, 'Ghannouch', 5);
INSERT INTO cities VALUES(43, 'Mareth', 5);
INSERT INTO cities VALUES(44, 'Matmata', 5);
INSERT INTO cities VALUES(45, 'Metouia', 5);
INSERT INTO cities VALUES(46, 'Nouvelle Matmata', 5);
INSERT INTO cities VALUES(47, 'Oudhref', 5);
INSERT INTO cities VALUES(48, 'Zarat', 5);
INSERT INTO cities VALUES(49, 'El Guettar', 6);
INSERT INTO cities VALUES(50, 'El Ksar', 6);
INSERT INTO cities VALUES(51, 'Gafsa', 6);
INSERT INTO cities VALUES(52, 'Mdhila', 6);
INSERT INTO cities VALUES(53, 'Metlaoui', 6);
INSERT INTO cities VALUES(54, 'Moulares', 6);
INSERT INTO cities VALUES(55, 'Redeyef', 6);
INSERT INTO cities VALUES(56, 'Sened', 6);
INSERT INTO cities VALUES(57, 'Ain Draham', 7);
INSERT INTO cities VALUES(58, 'Beni Mtir', 7);
INSERT INTO cities VALUES(59, 'Bou Salem', 7);
INSERT INTO cities VALUES(60, 'Fernana', 7);
INSERT INTO cities VALUES(61, 'Ghardimaou', 7);
INSERT INTO cities VALUES(62, 'Jendouba', 7);
INSERT INTO cities VALUES(63, 'Oued Melliz', 7);
INSERT INTO cities VALUES(64, 'Tabarka', 7);
INSERT INTO cities VALUES(65, 'Ain Djeloula', 8);
INSERT INTO cities VALUES(66, 'Alaa', 8);
INSERT INTO cities VALUES(67, 'Bou Hajla', 8);
INSERT INTO cities VALUES(68, 'Chebika', 8);
INSERT INTO cities VALUES(69, 'Echrarda', 8);
INSERT INTO cities VALUES(70, 'Oueslatia', 8);
INSERT INTO cities VALUES(71, 'Haffouz', 8);
INSERT INTO cities VALUES(72, 'Hajeb El Ayoun', 8);
INSERT INTO cities VALUES(73, 'Kairouan', 8);
INSERT INTO cities VALUES(74, 'Menzel Mehiri', 8);
INSERT INTO cities VALUES(75, 'Nasrallah', 8);
INSERT INTO cities VALUES(76, 'Sbikha', 8);
INSERT INTO cities VALUES(77, 'Feriana', 9);
INSERT INTO cities VALUES(78, 'Foussana', 9);
INSERT INTO cities VALUES(79, 'Haidra', 9);
INSERT INTO cities VALUES(80, 'Jedelienne', 9);
INSERT INTO cities VALUES(81, 'Kasserine', 9);
INSERT INTO cities VALUES(82, 'Magel Bel Abbes', 9);
INSERT INTO cities VALUES(83, 'Sbeitla', 9);
INSERT INTO cities VALUES(84, 'Sbiba', 9);
INSERT INTO cities VALUES(85, 'Thala', 9);
INSERT INTO cities VALUES(86, 'Thelepte', 9);
INSERT INTO cities VALUES(87, 'Douz', 10);
INSERT INTO cities VALUES(88, 'El Golaa', 10);
INSERT INTO cities VALUES(89, 'Jemna', 10);
INSERT INTO cities VALUES(90, 'Kebili', 10);
INSERT INTO cities VALUES(91, 'Souk Lahad', 10);
INSERT INTO cities VALUES(92, 'Dahmani', 11);
INSERT INTO cities VALUES(93, 'Jerissa', 11);
INSERT INTO cities VALUES(94, 'El Ksour', 11);
INSERT INTO cities VALUES(95, 'Kalaat Senan', 11);
INSERT INTO cities VALUES(96, 'Kalaat Khasba', 11);
INSERT INTO cities VALUES(97, 'Le Kef', 11);
INSERT INTO cities VALUES(98, 'Menzel Salem', 11);
INSERT INTO cities VALUES(99, 'Nebeur', 11);
INSERT INTO cities VALUES(100, 'Sakiet Sidi Youssef', 11);
INSERT INTO cities VALUES(101, 'Sers', 11);
INSERT INTO cities VALUES(102, 'Tajerouine', 11);
INSERT INTO cities VALUES(103, 'Touiref', 11);
INSERT INTO cities VALUES(104, 'Bou Merdes', 12);
INSERT INTO cities VALUES(105, 'Chebba', 12);
INSERT INTO cities VALUES(106, 'Chorbane', 12);
INSERT INTO cities VALUES(107, 'El Bradaa', 12);
INSERT INTO cities VALUES(108, 'El Jem', 12);
INSERT INTO cities VALUES(109, 'Essouassi', 12);
INSERT INTO cities VALUES(110, 'Hebira', 12);
INSERT INTO cities VALUES(111, 'Hiboun', 12);
INSERT INTO cities VALUES(112, 'Kerker', 12);
INSERT INTO cities VALUES(113, 'Ksour Essef', 12);
INSERT INTO cities VALUES(114, 'Mahdia', 12);
INSERT INTO cities VALUES(115, 'Mellouleche', 12);
INSERT INTO cities VALUES(116, 'Ouled Chamekh', 12);
INSERT INTO cities VALUES(117, 'Rejiche', 12);
INSERT INTO cities VALUES(118, 'Sidi Alouane', 12);
INSERT INTO cities VALUES(119, 'Borj El Amri', 13);
INSERT INTO cities VALUES(120, 'Den Den', 13);
INSERT INTO cities VALUES(121, 'Douar Hicher', 13);
INSERT INTO cities VALUES(122, 'Djedeida', 13);
INSERT INTO cities VALUES(123, 'El Battan', 13);
INSERT INTO cities VALUES(124, 'Oued Ellil', 13);
INSERT INTO cities VALUES(125, 'La Manouba', 13);
INSERT INTO cities VALUES(126, 'Mornaguia', 13);
INSERT INTO cities VALUES(127, 'Tebourba', 13);
INSERT INTO cities VALUES(128, 'Ajim', 14);
INSERT INTO cities VALUES(129, 'Ben Gardane', 14);
INSERT INTO cities VALUES(130, 'Beni Khedache', 14);
INSERT INTO cities VALUES(131, 'Houmt Souk', 14);
INSERT INTO cities VALUES(132, 'Medenine', 14);
INSERT INTO cities VALUES(133, 'Midoun', 14);
INSERT INTO cities VALUES(134, 'Zarzis', 14);
INSERT INTO cities VALUES(135, 'Amiret El Fhoul', 15);
INSERT INTO cities VALUES(136, 'Amiret El Hojjaj', 15);
INSERT INTO cities VALUES(137, 'Amiret Touazra', 15);
INSERT INTO cities VALUES(138, 'Bekalta', 15);
INSERT INTO cities VALUES(139, 'Bembla', 15);
INSERT INTO cities VALUES(140, 'Beni Hassen', 15);
INSERT INTO cities VALUES(141, 'Bennane', 15);
INSERT INTO cities VALUES(142, 'Bouhjar', 15);
INSERT INTO cities VALUES(143, 'Cherahil', 15);
INSERT INTO cities VALUES(144, 'El Masdour', 15);
INSERT INTO cities VALUES(145, 'Ghenada', 15);
INSERT INTO cities VALUES(146, 'Jemmal', 15);
INSERT INTO cities VALUES(147, 'Khniss', 15);
INSERT INTO cities VALUES(148, 'Ksar Hellal', 15);
INSERT INTO cities VALUES(149, 'Ksibet el-Mediouni', 15);
INSERT INTO cities VALUES(150, 'Lamta', 15);
INSERT INTO cities VALUES(151, 'Menzel Farsi', 15);
INSERT INTO cities VALUES(152, 'Menzel Hayet', 15);
INSERT INTO cities VALUES(153, 'Menzel Kamel', 15);
INSERT INTO cities VALUES(154, 'Moknine', 15);
INSERT INTO cities VALUES(155, 'Monastir', 15);
INSERT INTO cities VALUES(156, 'Ouerdanin', 15);
INSERT INTO cities VALUES(157, 'Azmour', 16);
INSERT INTO cities VALUES(158, 'Beni Khalled', 16);
INSERT INTO cities VALUES(159, 'Beni Khiar', 16);
INSERT INTO cities VALUES(160, 'Bou Argoub', 16);
INSERT INTO cities VALUES(161, 'Dar Allouch', 16);
INSERT INTO cities VALUES(162, 'Dar Chaabane', 16);
INSERT INTO cities VALUES(163, 'El Haouaria', 16);
INSERT INTO cities VALUES(164, 'El Maamoura', 16);
INSERT INTO cities VALUES(165, 'El Mida', 16);
INSERT INTO cities VALUES(166, 'Grombalia', 16);
INSERT INTO cities VALUES(167, 'Hammam Ghezeze', 16);
INSERT INTO cities VALUES(168, 'Hammamet', 16);
INSERT INTO cities VALUES(169, 'Kelibia', 16);
INSERT INTO cities VALUES(170, 'Kerkouane', 16);
INSERT INTO cities VALUES(171, 'Korba', 16);
INSERT INTO cities VALUES(172, 'Korbous', 16);
INSERT INTO cities VALUES(173, 'Menzel Bouzelfa', 16);
INSERT INTO cities VALUES(174, 'Menzel Horr', 16);
INSERT INTO cities VALUES(175, 'Menzel Temime', 16);
INSERT INTO cities VALUES(176, 'Nabeul', 16);
INSERT INTO cities VALUES(177, 'Soliman', 16);
INSERT INTO cities VALUES(178, 'Somaa', 16);
INSERT INTO cities VALUES(179, 'Takelsa', 16);
INSERT INTO cities VALUES(180, 'Tazerka', 16);
INSERT INTO cities VALUES(181, 'Zaouiet Djedidi', 16);
INSERT INTO cities VALUES(182, 'Agareb', 17);
INSERT INTO cities VALUES(183, 'Bir Ali Ben Khelifa', 17);
INSERT INTO cities VALUES(184, 'Bir Salah', 17);
INSERT INTO cities VALUES(185, 'Chihia', 17);
INSERT INTO cities VALUES(186, 'El Ain', 17);
INSERT INTO cities VALUES(187, 'Graiba', 17);
INSERT INTO cities VALUES(188, 'Gremda', 17);
INSERT INTO cities VALUES(189, 'Jebiniana', 17);
INSERT INTO cities VALUES(190, 'Kerkennah', 17);
INSERT INTO cities VALUES(191, 'El Hencha', 17);
INSERT INTO cities VALUES(192, 'Mahres', 17);
INSERT INTO cities VALUES(193, 'Menzel Chaker', 17);
INSERT INTO cities VALUES(194, 'Sakiet Eddaier', 17);
INSERT INTO cities VALUES(195, 'Sakiet Ezzit', 17);
INSERT INTO cities VALUES(196, 'Sfax', 17);
INSERT INTO cities VALUES(197, 'Skhira', 17);
INSERT INTO cities VALUES(198, 'Thyna', 17);
INSERT INTO cities VALUES(199, 'Bir El Hafey', 18);
INSERT INTO cities VALUES(200, 'Cebbala Ouled Asker', 18);
INSERT INTO cities VALUES(201, 'Jilma', 18);
INSERT INTO cities VALUES(202, 'Jilma', 18);
INSERT INTO cities VALUES(203, 'Menzel Bouzaiane', 18);
INSERT INTO cities VALUES(204, 'Meknassy', 18);
INSERT INTO cities VALUES(205, 'Mezzouna', 18);
INSERT INTO cities VALUES(206, 'Ouled Haffouz', 18);
INSERT INTO cities VALUES(207, 'Regueb', 18);
INSERT INTO cities VALUES(208, 'Sidi Ali Ben Aoun', 18);
INSERT INTO cities VALUES(209, 'Sidi Bou Zid', 18);
INSERT INTO cities VALUES(210, 'Bargou', 19);
INSERT INTO cities VALUES(211, 'Bou Arada', 19);
INSERT INTO cities VALUES(212, 'El Aroussa', 19);
INSERT INTO cities VALUES(213, 'El Krib', 19);
INSERT INTO cities VALUES(214, 'Gaafour', 19);
INSERT INTO cities VALUES(215, 'Kesra', 19);
INSERT INTO cities VALUES(216, 'Makthar', 19);
INSERT INTO cities VALUES(217, 'Rouhia', 19);
INSERT INTO cities VALUES(218, 'Sidi Bou Rouis', 19);
INSERT INTO cities VALUES(219, 'Siliana', 19);
INSERT INTO cities VALUES(220, 'Akouda', 20);
INSERT INTO cities VALUES(221, 'Bouficha', 20);
INSERT INTO cities VALUES(222, 'Enfida', 20);
INSERT INTO cities VALUES(223, 'Ezzouhour', 20);
INSERT INTO cities VALUES(224, 'Hammam Sousse', 20);
INSERT INTO cities VALUES(225, 'Hergla', 20);
INSERT INTO cities VALUES(226, 'Kalaa Kebira', 20);
INSERT INTO cities VALUES(227, 'Kalaa Seghira', 20);
INSERT INTO cities VALUES(228, 'Kondar', 20);
INSERT INTO cities VALUES(229, 'Ksibet Thrayet', 20);
INSERT INTO cities VALUES(230, 'Messaadine', 20);
INSERT INTO cities VALUES(231, 'Msaken', 20);
INSERT INTO cities VALUES(232, 'Sousse', 20);
INSERT INTO cities VALUES(233, 'Sidi Bou Ali', 20);
INSERT INTO cities VALUES(234, 'Sidi El Hani', 20);
INSERT INTO cities VALUES(235, 'Zaouiet Sousse', 20);
INSERT INTO cities VALUES(236, 'Bir Lahmar', 21);
INSERT INTO cities VALUES(237, 'Dehiba', 21);
INSERT INTO cities VALUES(238, 'Ghomrassen', 21);
INSERT INTO cities VALUES(239, 'Remada', 21);
INSERT INTO cities VALUES(240, 'Tataouine', 21);
INSERT INTO cities VALUES(241, 'Degache', 22);
INSERT INTO cities VALUES(242, 'El Hamma du Jerid', 22);
INSERT INTO cities VALUES(243, 'Nefta', 22);
INSERT INTO cities VALUES(244, 'Tamerza', 22);
INSERT INTO cities VALUES(245, 'Tozeur', 22);
INSERT INTO cities VALUES(246, 'Carthage', 23);
INSERT INTO cities VALUES(247, 'La Goulette', 23);
INSERT INTO cities VALUES(248, 'La Marsa', 23);
INSERT INTO cities VALUES(249, 'Le Bardo', 23);
INSERT INTO cities VALUES(250, 'Le Kram', 23);
INSERT INTO cities VALUES(251, 'Sidi Bou Said', 23);
INSERT INTO cities VALUES(252, 'Sidi Hassine', 23);
INSERT INTO cities VALUES(253, 'Tunis', 23);
INSERT INTO cities VALUES(254, 'El Fahs', 24);
INSERT INTO cities VALUES(255, 'Djebel Oust', 24);
INSERT INTO cities VALUES(256, 'Bir Mcherga', 24);
INSERT INTO cities VALUES(257, 'Nadhour', 24);
INSERT INTO cities VALUES(258, 'Zaghouan', 24);
INSERT INTO cities VALUES(259, 'Zriba', 24);
